tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar
  name: Run PetClinic app
 
# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot

jetbrains:
  intellij:
    prebuilds:
      version: both
